# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewsApp_without_Storyboard' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewsApp_without_Storyboard
pod 'SDWebImage'

end
